### ISSUE TITLE
Latest FusionFix + ConsoleVehicleAnims.img causes crashes in TBOGT

### ISSUE THREAD

**Issue by viennaontheline** [Tomasak/Console-Visuals#2] opened 2024-08-25 13:11 UTC
Latest FusionFix + ConsoleVehicleAnims.img causes crashes in TBOGT, also causes white in-game map and then crashes

**Comment by Abbanon** [comment] 2024-08-26 17:11
I can confirm that I've been experiencing similar white-map crashes in the base GTA IV campaign.
It happens when I hit Esc to view the map on the pause screen.
But I'm not entirely sure what mods cause it on my end.
Here's a collection of several crashdumps:
[crashdumps.zip](https://github.com/user-attachments/files/16751638/crashdumps.zip)

**Comment by Abbanon** [comment] 2024-08-27 06:09
I've also reported this here in case it's not related to Console Visuals:
https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/issues/587

**Comment by RecklessGlue540** [comment] 2024-09-05 09:10
Can be closed as reason seems to be higher resolution minimap mods after all..

**Comment by viennaontheline** [comment] 2024-09-05 10:10
> Can be closed as reason seems to be higher resolution minimap mods after all..

Not. Conflicts FF + ConsoleVehicleAnims.img it's another bug.

**Closed as completed** 2024-12-05 08:49 UTC
